BEGIN TRANSACTION;

CREATE TABLE "User" ( "UserName" TEXT NOT NULL UNIQUE, PRIMARY KEY ("UserName") );
CREATE TABLE "RecordType" ( "RecordType" TEXT NOT NULL UNIQUE, PRIMARY KEY ("RecordType") );
CREATE TABLE "Ability" ( "Ability" TEXT NOT NULL UNIQUE COLLATE NOCASE, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("Ability"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "Condition" ( "Condition" TEXT NOT NULL UNIQUE COLLATE NOCASE, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("Condition"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "ConditionEffect" ( "Condition" TEXT NOT NULL COLLATE NOCASE, "EffectID" INTEGER NOT NULL, "Description" TEXT NOT NULL, PRIMARY KEY ("EffectID", "Condition"), FOREIGN KEY ("Condition") REFERENCES "Condition" ("Condition") ON DELETE CASCADE );
CREATE TABLE "DamageType" ( "DamageType" TEXT NOT NULL UNIQUE COLLATE NOCASE, "Description" TEXT NOT NULL, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("DamageType"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "Language" ( "Language" TEXT NOT NULL UNIQUE, "Description" INTEGER NOT NULL, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("Language"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "Size" ( "Size" TEXT NOT NULL UNIQUE, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("Size"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "Alignment" ( "Alignment" TEXT NOT NULL UNIQUE, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("Alignment"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "EntityType" ( "EntityType" TEXT NOT NULL UNIQUE, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("EntityType"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "ModifierType" ( "ModifierType" TEXT NOT NULL UNIQUE, "Description" TEXT NOT NULL, "IsProficiencyRelevant" TEXT NOT NULL DEFAULT '' CHECK ("IsProficiencyRelevant" in ('', 'X')), "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("ModifierType"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "StatBlock" ( "StatBlockID" INTEGER NOT NULL UNIQUE, "Name" TEXT NOT NULL COLLATE NOCASE, "ChallengeRating" NUMERIC NOT NULL CHECK ("ChallengeRating" >= 0), "ProficiencyBonus" INTEGER NOT NULL CHECK ("ProficiencyBonus" >= 2), "Source" TEXT NOT NULL, "Size" TEXT NOT NULL, "Type" TEXT NOT NULL, "Alignment" TEXT DEFAULT 'Any', "ArmorClass" INTEGER NOT NULL, "HitPoints1" INTEGER NOT NULL, "HitPoints2" TEXT NOT NULL, "SWalk" INTEGER NOT NULL DEFAULT 0 CHECK ("SWalk" >= 0), "SFly" INTEGER NOT NULL DEFAULT 0 CHECK ("SFly" >= 0), "SClimb" INTEGER NOT NULL DEFAULT 0 CHECK ("Sclimb" >= 0), "SSwim" INTEGER NOT NULL DEFAULT 0 CHECK ("SSwim" >= 0), "SBurrow" INTEGER NOT NULL DEFAULT 0 CHECK ("SBurrow" >= 0), "ReactionCount" INTEGER NOT NULL DEFAULT 1 CHECK ("ReactionCount" >= 0), "ArmorType" TEXT NOT NULL, "RecordType" TEXT NOT NULL, "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("StatBlockID" AUTOINCREMENT), FOREIGN KEY ("Size") REFERENCES "Size" ("Size"), FOREIGN KEY ("Type") REFERENCES "EntityType" ("EntityType"), FOREIGN KEY ("RecordType") REFERENCES "RecordType" ("RecordType"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "EntityStats" ( "StatBlockID" INTEGER NOT NULL, "Ability" TEXT NOT NULL CHECK (length ("Ability") > 0), "Value" INTEGER NOT NULL DEFAULT 10 CHECK ("Value" >= 0), PRIMARY KEY ("StatBlockID", "Ability"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE, FOREIGN KEY ("Ability") REFERENCES "Ability" ("Ability") ON DELETE CASCADE );
CREATE TABLE "Modifiers" ( "StatBlockID" INTEGER NOT NULL, "Item" INTEGER NOT NULL CHECK ("Item" >= 0), "Type" TEXT NOT NULL CHECK ("Type" NOT IN ('SK', 'ST')), "Name" TEXT NOT NULL, "Value" INTEGER DEFAULT 0, "Description" TEXT DEFAULT '', PRIMARY KEY ("StatBlockID", "Item"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE, FOREIGN KEY ("Type") REFERENCES "ModifierType" ("ModifierType") ON DELETE CASCADE );
CREATE TABLE "Proficiencies" ( "StatBlockID" INTEGER NOT NULL, "Item" INTEGER NOT NULL CHECK ("Item" >= 0), "Type" TEXT NOT NULL CHECK ("Type" IN ('SK', 'ST')), "Name" TEXT NOT NULL, "Level" INTEGER DEFAULT 0, "Override" INTEGER DEFAULT 0, PRIMARY KEY ("StatBlockID", "Item"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE, FOREIGN KEY ("Type") REFERENCES "ModifierType" ("ModifierType") ON DELETE CASCADE );
CREATE TABLE "Action" ( "StatBlockID" INTEGER NOT NULL, "ActionID" INTEGER NOT NULL CHECK ("ActionID" >= 0), "Name" TEXT DEFAULT '', "AttackType" TEXT DEFAULT '', "HitModifier" INTEGER DEFAULT 0, "Reach" INTEGER DEFAULT 0, "Targets" INTEGER DEFAULT 0, "Description" TEXT DEFAULT '', PRIMARY KEY ("StatBlockID", "ActionID"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE TABLE "ActionDamage" ( "StatBlockID" INTEGER NOT NULL, "ActionID" INTEGER NOT NULL, "DamageID" INTEGER NOT NULL, "Amount" TEXT DEFAULT '', "Type" TEXT DEFAULT '', "AltDmgActive" TEXT DEFAULT '' CHECK ("AltDmgActive" IN ('X', '')) COLLATE NOCASE, "Amount2" TEXT DEFAULT '', "Type2" TEXT DEFAULT '', "AltDmgNote" TEXT DEFAULT '', "SaveDmgActive" TEXT DEFAULT '' CHECK ("SaveDmgActive" IN ('X', '')) COLLATE NOCASE, "Ability" TEXT DEFAULT '', "DC" INTEGER DEFAULT 0, "HalfDamage" TEXT DEFAULT '' CHECK ("HalfDamage" IN ('X', '')) COLLATE NOCASE, "SaveDmgNote" TEXT DEFAULT '', PRIMARY KEY ("StatBlockID", "ActionID", "DamageID"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE, FOREIGN KEY ("StatBlockID", "ActionID") REFERENCES "Action" ("StatBlockID", "ActionID") ON DELETE CASCADE, FOREIGN KEY ("Type") REFERENCES "DamageType" ("DamageType"), FOREIGN KEY ("Type2") REFERENCES "DamageType" ("DamageType"), FOREIGN KEY ("Ability") REFERENCES "Ability" ("Ability") );
CREATE TABLE "Campaign" ( "Campaign" TEXT NOT NULL UNIQUE CHECK ("Campaign" <> ''), "Domain" TEXT NOT NULL, "Description" TEXT DEFAULT '', PRIMARY KEY ("Campaign", "Domain"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "Encounter" ( "EncounterID" INTEGER NOT NULL UNIQUE CHECK ("EncounterID" > 0), "Name" TEXT DEFAULT '', "Description" TEXT DEFAULT '', "CreationDate" TEXT NOT NULL CHECK (length ("CreationDate") = 8), "AccessedDate" TEXT NOT NULL CHECK (length ("AccessedDate") = 8), "Campaign" TEXT DEFAULT '', "Started" TEXT DEFAULT '' CHECK ("Started" IN ('X', '')) COLLATE NOCASE, "Round" INTEGER DEFAULT 0, "Turn" INTEGER DEFAULT 0, "HasLair" TEXT DEFAULT '' CHECK ("HasLair" IN ('X', '')) COLLATE NOCASE, "LairOwnerID" INTEGER DEFAULT -1, "ActiveID" TEXT DEFAULT '', "Domain" TEXT NOT NULL DEFAULT 'Public', "Published" TEXT NOT NULL DEFAULT '' CHECK ("Published" in ('', 'X')), PRIMARY KEY ("EncounterID" AUTOINCREMENT), FOREIGN KEY ("Campaign", "Domain") REFERENCES "Campaign" ("Campaign", "Domain") ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "EncounterEntities" ( "EncounterID" INTEGER NOT NULL, "RowID" INTEGER NOT NULL, "StatBlockID" INTEGER NOT NULL, "Suffix" TEXT DEFAULT '', "Initiative" INTEGER DEFAULT 0, "MaxHitPoints" INTEGER NOT NULL, "TempHitPoints" INTEGER DEFAULT 0, "CurrentHitPoints" INTEGER NOT NULL, "ArmorClassBonus" INTEGER DEFAULT 0, "Concentration" TEXT DEFAULT '' CHECK ("Concentration" IN ('X', '')) COLLATE NOCASE, "Notes" TEXT DEFAULT '', "IsHostile" TEXT DEFAULT 'X' CHECK ("IsHostile" IN ('X', '')) COLLATE NOCASE, "EncounterLocked" TEXT DEFAULT '' CHECK ("EncounterLocked" IN ('X', '')) COLLATE NOCASE, "ID" TEXT NOT NULL DEFAULT '', PRIMARY KEY ("EncounterID", "RowID"), FOREIGN KEY ("EncounterID") REFERENCES "Encounter" ("EncounterID") ON DELETE CASCADE, FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE TABLE "EncEntConditions" ( "EncounterID" INTEGER NOT NULL, "RowID" INTEGER NOT NULL, "Condition" TEXT NOT NULL, "Duration" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("EncounterID", "RowID", "Condition"), FOREIGN KEY ("EncounterID", "RowID") REFERENCES "EncounterEntities" ("EncounterID", "RowID") ON DELETE CASCADE, FOREIGN KEY ("Condition") REFERENCES "Condition" ("Condition") ON DELETE CASCADE );
CREATE TABLE "Lair" ( "StatBlockID" INTEGER NOT NULL, "Name" TEXT, "Description" TEXT, "Initiative" INTEGER CHECK (Initiative >= 0), PRIMARY KEY ("StatBlockID"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE TABLE "SimpleAction" ( "StatBlockID" INTEGER NOT NULL, "ActionID" INTEGER NOT NULL, "Type" TEXT NOT NULL CHECK ("Type" IN ('Bonus', 'Reaction')), "Name" TEXT NOT NULL, "Description" TEXT NOT NULL, PRIMARY KEY ("StatBlockID", "ActionID"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE TABLE "SpokenLanguage" ( "StatBlockID" INTEGER NOT NULL, "Language" TEXT NOT NULL, "Description" TEXT DEFAULT '', PRIMARY KEY ("Language", "StatBlockID"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE, FOREIGN KEY ("Language") REFERENCES "Language" ("Language") ON DELETE CASCADE );
CREATE TABLE "SuperAction" ( "StatBlockID" INTEGER NOT NULL, "ActionID" INTEGER NOT NULL, "Type" TEXT NOT NULL CHECK ("Type" IN ('Legendary', 'Mythic', 'Lair')), "Name" TEXT NOT NULL DEFAULT 'X', "Description" TEXT NOT NULL, "Points" INTEGER NOT NULL, "IsRegional" TEXT CHECK ("IsRegional" in ('X', '')) COLLATE NOCASE, PRIMARY KEY ("StatBlockID", "ActionID", "Type"), FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE TABLE "CampaignEntities" ( "Campaign" TEXT NOT NULL, "Domain" TEXT NOT NULL, "RowID" INTEGER NOT NULL, "StatBlockID" INTEGER NOT NULL, "Notes" TEXT DEFAULT '', PRIMARY KEY ("Campaign", "Domain", "RowID"), FOREIGN KEY ("Domain") REFERENCES "User" ("UserName") ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY ("Campaign", "Domain") REFERENCES "Campaign" ("Campaign", "Domain") ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY ("StatBlockID") REFERENCES "StatBlock" ("StatBlockID") ON DELETE CASCADE );
CREATE VIEW LairActionV AS SELECT StatBlockID, Name, Description, coalesce(IsRegional, '') as IsRegional, Domain, Published FROM SuperAction WHERE Type = 'Lair';
CREATE VIEW SuperActionHV AS SELECT StatBlockID, Type, Description, Points, Domain, Published FROM SuperAction WHERE Type in ('Legendary', 'Mythic') AND Name = 'X';
CREATE VIEW SuperActionV AS SELECT StatBlockID, Type, Name, Description, Points, Domain, Published FROM SuperAction WHERE Type in ('Legendary', 'Mythic') and Name <> 'X';

COMMIT;

PRAGMA INTEGRITY_CHECK;
