CREATE TABLE "Entity" (
	"EntityID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"ChallengeRating"	NUMERIC NOT NULL CHECK(ChallengeRating >= 0),
	"ProficiencyBonus"	INTEGER NOT NULL CHECK(ProficiencyBonus >= 2),
	"Source"	TEXT NOT NULL,
	"Size"	TEXT NOT NULL,
	"Type"	TEXT NOT NULL,
	"Alignment"	TEXT DEFAULT 'Any',
	"ArmorClass"	INTEGER NOT NULL,
	"HitPoints1"	INTEGER NOT NULL,
	"HitPoints2"	TEXT NOT NULL,
	"SWalk"	INTEGER NOT NULL DEFAULT 0 CHECK(SWalk >= 0),
	"SFly"	INTEGER NOT NULL DEFAULT 0 CHECK(SFly >= 0),
	"SClimb"	INTEGER NOT NULL DEFAULT 0 CHECK(Sclimb >= 0),
	"SSwim"	INTEGER NOT NULL DEFAULT 0 CHECK(SSwim >= 0),
	"SBurrow"	INTEGER NOT NULL DEFAULT 0 CHECK(SBurrow >= 0),
	"ReactionCount"	INTEGER NOT NULL DEFAULT 1 CHECK(ReactionCount >= 0),
	"Strength"	INTEGER NOT NULL CHECK(Strength > 0),
	"Dexterity"	INTEGER NOT NULL CHECK(Dexterity > 0),
	"Constitution"	INTEGER NOT NULL CHECK(Constitution > 0),
	"Intelligence"	INTEGER NOT NULL CHECK(Intelligence > 0),
	"Wisdom"	INTEGER NOT NULL CHECK(Wisdom > 0),
	"Charisma"	INTEGER NOT NULL CHECK(Charisma > 0),
	"ArmorType"	TEXT NOT NULL,
	PRIMARY KEY("EntityID" AUTOINCREMENT),
	FOREIGN KEY("Size") REFERENCES "Size"("Size"),
	FOREIGN KEY("Type") REFERENCES "EntityType"("EntityType")
)